from starkbank.iso8583.utils.enum import LengthType


def parseString(text):
    return text


def parseBin(text):
    return text


def parseHexToBin(text, length=64):
    return bin(int(text, 16))[2:].zfill(length)


def parseBytesToBin(text, length=64):
    return parseHexToBin(text.encode("cp500").hex(), length=length)


mastercard = {
    "MTI": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE000": {"type": LengthType.FIXED, "limit": 8, "parser": parseBytesToBin},
    "DE001": {"type": LengthType.FIXED, "limit": 8, "parser": parseBytesToBin},
    "DE002": {"type": LengthType.LLVAR, "limit": 19, "parser": parseString},
    "DE003": {"type": LengthType.FIXED, "limit": 6, "parser": parseString},
    "DE004": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE005": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE006": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE007": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE008": {"type": LengthType.FIXED, "limit": 8, "parser": parseString},
    "DE009": {"type": LengthType.FIXED, "limit": 8, "parser": parseString},
    "DE010": {"type": LengthType.FIXED, "limit": 8, "parser": parseString},
    "DE011": {"type": LengthType.FIXED, "limit": 6, "parser": parseString},
    "DE012": {"type": LengthType.FIXED, "limit": 6, "parser": parseString},
    "DE013": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE014": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE015": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE016": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE017": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE018": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE019": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE020": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE021": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE022": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE023": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE024": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE025": {"type": LengthType.FIXED, "limit": 2, "parser": parseString},
    "DE026": {"type": LengthType.FIXED, "limit": 2, "parser": parseString},
    "DE027": {"type": LengthType.FIXED, "limit": 1, "parser": parseString},
    "DE028": {"type": LengthType.FIXED, "limit": 9, "parser": parseString},
    "DE029": {"type": LengthType.FIXED, "limit": 9, "parser": parseString},
    "DE030": {"type": LengthType.FIXED, "limit": 9, "parser": parseString},
    "DE031": {"type": LengthType.FIXED, "limit": 9, "parser": parseString},
    "DE032": {"type": LengthType.LLVAR, "limit": 11, "parser": parseString},
    "DE033": {"type": LengthType.LLVAR, "limit": 11, "parser": parseString},
    "DE034": {"type": LengthType.LLVAR, "limit": 28, "parser": parseString},
    "DE035": {"type": LengthType.LLVAR, "limit": 37, "parser": parseString},
    "DE036": {"type": LengthType.LLLVAR, "limit": 104, "parser": parseString},
    "DE037": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE038": {"type": LengthType.FIXED, "limit": 6, "parser": parseString},
    "DE039": {"type": LengthType.FIXED, "limit": 2, "parser": parseString},
    "DE040": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE041": {"type": LengthType.FIXED, "limit": 8, "parser": parseString},
    "DE042": {"type": LengthType.FIXED, "limit": 15, "parser": parseString},
    "DE043": {"type": LengthType.FIXED, "limit": 40, "parser": parseString},
    "DE044": {"type": LengthType.LLVAR, "limit": 25, "parser": parseString},
    "DE045": {"type": LengthType.LLVAR, "limit": 76, "parser": parseString},
    "DE046": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE047": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE048": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE049": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE050": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE051": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE052": {"type": LengthType.FIXED, "limit": 16, "parser": parseBin},
    "DE053": {"type": LengthType.FIXED, "limit": 16, "parser": parseString},
    "DE054": {"type": LengthType.LLLVAR, "limit": 120, "parser": parseString},
    "DE055": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE056": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE057": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE058": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE059": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE060": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE061": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE062": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE063": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE064": {"type": LengthType.FIXED, "limit": 16, "parser": parseBin},
    "DE065": {"type": LengthType.FIXED, "limit": 8, "parser": parseBytesToBin},
    "DE066": {"type": LengthType.FIXED, "limit": 1, "parser": parseString},
    "DE067": {"type": LengthType.FIXED, "limit": 2, "parser": parseString},
    "DE068": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE069": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE070": {"type": LengthType.FIXED, "limit": 3, "parser": parseString},
    "DE071": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE072": {"type": LengthType.FIXED, "limit": 4, "parser": parseString},
    "DE073": {"type": LengthType.FIXED, "limit": 6, "parser": parseString},
    "DE074": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE075": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE076": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE077": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE078": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE079": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE080": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE081": {"type": LengthType.FIXED, "limit": 10, "parser": parseString},
    "DE082": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE083": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE084": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE085": {"type": LengthType.FIXED, "limit": 12, "parser": parseString},
    "DE086": {"type": LengthType.FIXED, "limit": 16, "parser": parseString},
    "DE087": {"type": LengthType.FIXED, "limit": 16, "parser": parseString},
    "DE088": {"type": LengthType.FIXED, "limit": 16, "parser": parseString},
    "DE089": {"type": LengthType.FIXED, "limit": 16, "parser": parseString},
    "DE090": {"type": LengthType.FIXED, "limit": 42, "parser": parseString},
    "DE091": {"type": LengthType.FIXED, "limit": 1, "parser": parseString},
    "DE092": {"type": LengthType.FIXED, "limit": 2, "parser": parseString},
    "DE093": {"type": LengthType.FIXED, "limit": 5, "parser": parseString},
    "DE094": {"type": LengthType.FIXED, "limit": 7, "parser": parseString},
    "DE095": {"type": LengthType.FIXED, "limit": 42, "parser": parseString},
    "DE096": {"type": LengthType.FIXED, "limit": 16, "parser": parseBin},
    "DE097": {"type": LengthType.FIXED, "limit": 17, "parser": parseString},
    "DE098": {"type": LengthType.FIXED, "limit": 25, "parser": parseString},
    "DE099": {"type": LengthType.LLVAR, "limit": 11, "parser": parseString},
    "DE100": {"type": LengthType.LLVAR, "limit": 11, "parser": parseString},
    "DE101": {"type": LengthType.LLVAR, "limit": 17, "parser": parseString},
    "DE102": {"type": LengthType.LLVAR, "limit": 28, "parser": parseString},
    "DE103": {"type": LengthType.LLVAR, "limit": 28, "parser": parseString},
    "DE104": {"type": LengthType.LLLVAR, "limit": 100, "parser": parseString},
    "DE105": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE106": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE107": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE108": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE109": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE110": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE111": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE112": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE113": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE114": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE115": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE116": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE117": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE118": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE119": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE120": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE121": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE122": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE123": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE124": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE125": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE126": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE127": {"type": LengthType.LLLVAR, "limit": 999, "parser": parseString},
    "DE128": {"type": LengthType.FIXED, "limit": 16, "parser": parseBin},
}
