from starkbank.iso8583.utils.enum import Encoding, LengthType
from starkbank.iso8583.utils.pad import padBcdString, unpadBcdString
from starkbank.iso8583.utils.header import parseVisaHeader, unparseVisaHeader
from starkbank.iso8583.utils.parser import parseString, parseBitString, parseBin, parseDE062, parseDE063
from starkbank.iso8583.utils.parser import unparseString, unparseBitString, unparseBin
from starkbank.iso8583.version import IsoVersion


visa = {
    IsoVersion._1987: {
        "Header": {
            "parser": parseVisaHeader,
            "unparser": unparseVisaHeader
        },
        "MTI": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,  # TODO: lengthEncoding: shouldn't be defined for lengthType == FIXED
            "dataEncoding": Encoding.bcd,
        },
        "DE000": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseBitString,
            "unparser": unparseBitString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.binary,
        },
        "DE001": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseBitString,
            "unparser": unparseBitString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.binary,
        },
        "DE002": {
            "lengthType": LengthType.llvar,
            "limit": 19,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE003": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE004": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE005": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE006": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE007": {
            "lengthType": LengthType.fixed,
            "limit": 10,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE008": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE009": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE010": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE011": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE012": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE013": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE014": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE015": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE016": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE017": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.cp500,
            "dataEncoding": Encoding.cp500,
        },
        "DE018": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE019": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE022": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE023": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE025": {
            "lengthType": LengthType.fixed,
            "limit": 2,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE032": {
            "lengthType": LengthType.llvar,
            "limit": 11,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE035": {
            "lengthType": LengthType.llvar,
            "limit": 37,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE037": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.cp500,
            "dataEncoding": Encoding.cp500,
        },
        "DE041": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.cp500,
            "dataEncoding": Encoding.cp500
        },
        "DE042": {
            "lengthType": LengthType.fixed,
            "limit": 15,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.cp500,
            "dataEncoding": Encoding.cp500,
        },
        "DE043": {
            "lengthType": LengthType.fixed,
            "limit": 40,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.cp500,
            "dataEncoding": Encoding.cp500,
        },
        "DE049": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE052": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseBitString,
            "unparser": unparseBitString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE053": {
            "lengthType": LengthType.fixed,
            "limit": 16,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.bcd,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE055": {
            "lengthType": LengthType.llvar,  # TODO: llvar used to force 1 length byte
            "limit": 255,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE059": {
            "lengthType": LengthType.llvar,
            "limit": 14,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE060": {
            "lengthType": LengthType.llvar,
            "limit": 12,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,  # TODO: problem
        },
        "DE061": {
            "lengthType": LengthType.llvar,
            "limit": 24,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,  # TODO: problem
        },
        "DE062": {
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseBin,  # TODO: replace by parseDE062
            "unparser": unparseBin,  # TODO: add unparseDE062
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE063": {
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseBin,
            "unparser": unparseBin,  # TODO: add unparseDE063
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
    }
}
