from starkbank.iso8583.utils.enum import Encoding, LengthType
from starkbank.iso8583.utils.pad import padBcdString, unpadBcdString
from starkbank.iso8583.utils.header import parseVisaHeader, unparseVisaHeader
from starkbank.iso8583.utils.parser import parseString, parseBitString, parseBin, parseDE062, parseDE063, unparseDE062
from starkbank.iso8583.utils.parser import unparseString, unparseBitString, unparseBin
from starkbank.iso8583.version import IsoVersion

# Template
#
# {
#             "lengthType": LengthType.,
#             "limit": ,
#             "parser": ,
#             "unparser": ,
#             "lengthEncoding": ,
#             "dataEncoding": ,
#         },

visa = {
    IsoVersion._1987: {
        "Header": {
            "parser": parseVisaHeader,
            "unparser": unparseVisaHeader
        },
        "MTI": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,  # TODO: lengthEncoding: shouldn't be defined for lengthType == FIXED
            "dataEncoding": Encoding.bcd,
        },
        "DE000": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseBitString,
            "unparser": unparseBitString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE001": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseBitString,
            "unparser": unparseBitString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE002": {
            "lengthType": LengthType.llvar,
            "limit": 19,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE003": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE004": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE005": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE006": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE007": {
            "lengthType": LengthType.fixed,
            "limit": 10,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE008": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE009": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE010": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE011": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE012": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE013": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE014": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE015": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE016": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE017": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE018": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE019": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE020": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE021": {
            "undefined": "",
        },
        "DE022": {
            "lengthType": LengthType.fixed,
            "limit": 4,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE023": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE024": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE025": {
            "lengthType": LengthType.fixed,
            "limit": 2,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE026": {
            "lengthType": LengthType.fixed,
            "limit": 2,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE027": {
            "undefined": "",
        },
        "DE028": {
            "lengthType": LengthType.fixed,
            "limit": 9,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE029": {
            "undefined": "",
        },
        "DE030": {
            "undefined": "",
        },
        "DE031": {
            "undefined": "",
        },
        "DE032": {
            "lengthType": LengthType.llvar,
            "limit": 11,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE033": {
            "lengthType": LengthType.llvar,
            "limit": 11,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE034": {  # TODO: delay processing to card processor? Needs parseDE034?
            "lengthType": LengthType.llllvar,
            "limit": 9999,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE035": {
            "lengthType": LengthType.llvar,
            "limit": 37,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE036": {
            "lengthType": LengthType.llvar,
            "limit": 104,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE037": {
            "lengthType": LengthType.fixed,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE038": {
            "lengthType": LengthType.fixed,
            "limit": 6,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE039": {
            "lengthType": LengthType.fixed,
            "limit": 2,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE040": {
            "undefined": "",
        },
        "DE041": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE042": {
            "lengthType": LengthType.fixed,
            "limit": 15,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE043": {
            "lengthType": LengthType.fixed,
            "limit": 40,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE044": {
            "lengthType": LengthType.llvar,
            "limit": 25,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE045": {
            "lengthType": LengthType.llvar,
            "limit": 76,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE046": {
            "lengthType": LengthType.llvar,  # length exception
            "limit": 255,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE047": {
            "undefined": "",
        },
        "DE048": {
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE049": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE050": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE051": {
            "lengthType": LengthType.fixed,
            "limit": 3,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE052": {
            "lengthType": LengthType.fixed,
            "limit": 8,
            "parser": parseBitString,
            "unparser": unparseBitString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE053": {  # TODO: investigate alternative Usage 2 - 255 bytes
            "lengthType": LengthType.fixed,
            "limit": 16,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
        },
        "DE054": {
            "lengthType": LengthType.llvar,
            "limit": 120,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE055": {
            "lengthType": LengthType.llvar,  # TODO: length exception: llvar used to force 1 length byte
            "limit": 255,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE056": {  # TODO: there is an alternative definition
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE057": {
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE058": {
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseBin,
            "unparser": unparseBin,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE059": {
            "lengthType": LengthType.llvar,
            "limit": 14,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.cp500,
        },
        "DE060": {
            "lengthType": LengthType.llvar,
            "limit": 12,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE061": {
            "lengthType": LengthType.llvar,
            "limit": 36,
            "parser": parseString,
            "unparser": unparseString,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.bcd,
            "pad": padBcdString,
            "unpad": unpadBcdString,
        },
        "DE062": {
            "lengthType": LengthType.llvar,  # TODO: llvar to force 1-byte length encoding, despite having up to 255 bytes
            "limit": 255,
            "parser": parseDE062,
            "unparser": unparseDE062,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
        "DE063": {
            "lengthType": LengthType.llvar,
            "limit": 255,
            "parser": parseDE063,
            "unparser": unparseDE063,
            "lengthEncoding": Encoding.binary,
            "dataEncoding": Encoding.binary,
        },
    }
}
